# Generated by Django 4.2 on 2023-04-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affectiveApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('0', 'angry'), ('1', 'disgust'), ('2', 'fear'), ('3', 'happy'), ('4', 'neutral'), ('5', 'sad'), ('6', 'surprise')], default='4', max_length=10),
        ),
    ]
